### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by QuinnWang** [xmos/xmath_walkthrough#5]
Do the example projects support to run on Windows?
We have tried but encountered the problem as below when doing the “cmake --build build” after the successful cmake config step.
The cmake config step “cmake -B build -S xmath_walkthrough -DCMAKE_TOOLCHAIN_FILE=../xmos_cmake_toolchain/xs3a.cmake -G"NMake Makefiles” ran without any problem after fixed with 2 issues:
-       https://github.com/xmos/xmath_walkthrough/issues/2
-       https://github.com/xmos/xmath_walkthrough/issues/3

Error reported when doing the “cmake --build build”:
...
[ 60%] Linking C static library liblib_xcore_math.a
[ 60%] Built target lib_xcore_math
[ 60%] Building C object src/common/CMakeFiles/app_common.dir/file_utils/fileio.c.obj
[ 61%] Building C object src/common/CMakeFiles/app_common.dir/file_utils/wav_utils.c.obj
[ 61%] Building C object src/common/CMakeFiles/app_common.dir/timing/timing.c.obj
[ 61%] Building C object src/common/CMakeFiles/app_common.dir/wav_io/wav_io.c.obj
[ 62%] Linking C static library libapp_common.a
[ 62%] Built target app_common
[ 63%] Building C object src/part1A/CMakeFiles/part1A.dir/__/common/main.xc.obj
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Error: A00001 \x used with no following hex digits
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Error: A00001 \x used with no following hex digits
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Error: A00001 \x used with no following hex digits
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Warning: A00002 unknown escape sequence '\s'
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Warning: A00002 unknown escape sequence '\c'
C:\Users\USER~1\AppData\Local\Temp\ccgfTaaa.s:14: Warning: A00002 unknown escape sequence '\m'
NMAKE : fatal error U1077: “D:\Xmos\Tool\15.2.1\bin\xcc.exe”: return value “0x1”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: return value “0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: return value “0x2”
Stop.
 
D:\xmath_test>
 

BTW, the Windows environment:
-       Cmake: v3.26
-       Nmake: from VS 2019
-       XTC: v15.2.1

And, on Windows, before calling the cmake config command, we also need:
-       because the build system will use nmake, need to make sure the nmake environment variables were set up correctly, this was done with calling the Visual Studio built-in command line
-       also make sure XTC environment variables were set up properly, by call the setenv.bat in the same command line environment
 
There is no problem on my macOS. Thanks

**Comment by astewart-xmos** [comment]
Windows is supported, but only with either "Ninja" (recommended) or "Unix Makefiles" (using GNU Make for Windows) as the CMake generator.

The issue is ultimately with the handling of path separators in NMake and xcc.

The project `Makefile`s generated by NMake uses `\` (Windows-style) instead of `/` for path separators. Ninja and "Unix Makefiles" generates `Makefile`s with `/`.  It turns out that when compiling an `.xc` file, xcc mishandles the source file path and treats the `\` path separator as a string escape sequence (this doesn't happen for `.c` or `.S` files).

For undefined string escape sequences it gives a warning but still tries to compile the file, e.g.:

```
C:\Users\USER1\AppData\Local\Temp\ccgfTaaa.s:14: Warning: A00002 unknown escape sequence '\s'
```

For defined escape sequences like `\x`, it will error and fail to compile, e.g.:

```
C:\Users\USER1\AppData\Local\Temp\ccgfTaaa.s:14: Error: A00001 \x used with no following hex digits
```

I believe the xcc bug has already been fixed, but has not made it into a release yet.

So for now I recommend using [Ninja](https://ninja-build.org/) as your build tool. On the plus side, Ninja will also build much much faster than NMake.

**Comment by astewart-xmos** [comment]
Note: I should have mentioned that the project documentation will be updated to reflect this recommendation.
